services:
  web:
    build: .
    command: >
      ./wait-for-it.sh db:5432 -- bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@db:5432/fastapi_finance
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastapi_finance
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
